

function page_normal(){
    document.getElementsByClassName("left")[0].innerHTML = '<h2>輸入</h2> <form> <div class="input-group"> <label for="input1">主屬性：</label> <input type="text" id="mainV"> </div> <div class="input-group"> <label for="input2">副屬性：</label> <input type="text" id="subV"> </div> <div class="input-group"> <label for="input3">攻擊力（加成前）：</label> <input type="text" id="att"> </div> <!-- <div class="input-group"> <label for="input4">攻擊力％：</label> <input type="text" id="att_p"> </div> --> <div class="input-group"> <label for="input5">總傷害：</label> <input type="text" id="tot_a"> </div> <div class="input-group"> <label for="input6">Boss傷害：</label> <input type="text" id="boss_a"> </div> <div class="input-group"> <label for="input7">無視防禦（0 極限屬性）：</label> <input type="text" id="base_ig"> </div> <div class="input-group"> <label for="input8">爆擊傷害：</label> <input type="text" id="ctri_a"> </div> <div class="input-group"> <label for="input9">目標防禦％：</label> <input type="text" id="defense"> </div> <div class="input-group"> <label for="input10">剩餘點數：</label> <input type="text" id="points"> </div> <!-- 其他輸入框 --> </form> <button class="calculateBtn", onclick="example()">輸入範例</button>'
    document.getElementsByClassName("calculateBtn")[1].setAttribute("onclick", "calculate()") ;
    document.getElementById("output").innerHTML = "";
}
function page_DA(){
    document.getElementsByClassName("left")[0].innerHTML = '<h2>輸入（惡魔復仇者）</h2> <form> <div class="input-group"> <label for="input1">總血量：</label> <input type="text" id="HP"> </div> <div class="input-group"> <label for="input14">血量％（0 極限屬性）：</label> <input type="text" id="HP_p"> </div> <div class="input-group"> <label for="input11">不加成血量：</label> <input type="text" id="HP_wo"> </div> <div class="input-group"> <label for="input12">等級：</label> <input type="text" id="level"> </div> <div class="input-group"> <label for="input13">力量：</label> <input type="text" id="STR"> </div> <div class="input-group"> <label for="input3">攻擊力（加成前）：</label> <input type="text" id="att"> </div> <div class="input-group"> <label for="input5">總傷害：</label> <input type="text" id="tot_a"> </div> <div class="input-group"> <label for="input6">Boss傷害：</label> <input type="text" id="boss_a"> </div> <div class="input-group"> <label for="input7">無視防禦（0 極限屬性）：</label> <input type="text" id="base_ig"> </div> <div class="input-group"> <label for="input8">爆擊傷害：</label> <input type="text" id="ctri_a"> </div> <div class="input-group"> <label for="input9">目標防禦％：</label> <input type="text" id="defense"> </div> <div class="input-group"> <label for="input10">剩餘點數：</label> <input type="text" id="points"> </div> <!-- 其他輸入框 --> </form> <button class="calculateBtn", onclick="exampleDA()">輸入範例</button>'
    document.getElementsByClassName("calculateBtn")[1].setAttribute("onclick", "calculateDA()") ;
    document.getElementById("output").innerHTML = "";
}
function page_DS(){
    document.getElementsByClassName("left")[0].innerHTML = '<h2>輸入（雙副屬）</h2> <form> <div class="input-group"> <label for="input1">主屬性：</label> <input type="text" id="mainV"> </div> <div class="input-group"> <label for="input2">副屬性：</label> <input type="text" id="subV"> </div> <div class="input-group"> <label for="input15">副屬性2：</label> <input type="text" id="subV2"> </div> <div class="input-group"> <label for="input3">攻擊力（加成前）：</label> <input type="text" id="att"> </div> <!-- <div class="input-group"> <label for="input4">攻擊力％：</label> <input type="text" id="att_p"> </div> --> <div class="input-group"> <label for="input5">總傷害：</label> <input type="text" id="tot_a"> </div> <div class="input-group"> <label for="input6">Boss傷害：</label> <input type="text" id="boss_a"> </div> <div class="input-group"> <label for="input7">無視防禦（0 極限屬性）：</label> <input type="text" id="base_ig"> </div> <div class="input-group"> <label for="input8">爆擊傷害：</label> <input type="text" id="ctri_a"> </div> <div class="input-group"> <label for="input9">目標防禦％：</label> <input type="text" id="defense"> </div> <div class="input-group"> <label for="input10">剩餘點數：</label> <input type="text" id="points"> </div> <!-- 其他輸入框 --> <!-- 其他輸入框 --> </form> <button class="calculateBtn", onclick="exampleDS()">輸入範例</button>'
    document.getElementsByClassName("calculateBtn")[1].setAttribute("onclick", "calculateDS()") ;
    document.getElementById("output").innerHTML = "";
}
function page_Xenon(){
    document.getElementsByClassName("left")[0].innerHTML = '<h2>輸入（傑諾）</h2> <form> <div class="input-group"> <label for="input1">力量：</label> <input type="text" id="mainV"> </div> <div class="input-group"> <label for="input2">敏捷：</label> <input type="text" id="subV"> </div> <div class="input-group"> <label for="input15">幸運：</label> <input type="text" id="subV2"> </div> <div class="input-group"> <label for="input3">攻擊力（加成前）：</label> <input type="text" id="att"> </div> <!-- <div class="input-group"> <label for="input4">攻擊力％：</label> <input type="text" id="att_p"> </div> --> <div class="input-group"> <label for="input5">總傷害：</label> <input type="text" id="tot_a"> </div> <div class="input-group"> <label for="input6">Boss傷害：</label> <input type="text" id="boss_a"> </div> <div class="input-group"> <label for="input7">無視防禦（0 極限屬性）：</label> <input type="text" id="base_ig"> </div> <div class="input-group"> <label for="input8">爆擊傷害：</label> <input type="text" id="ctri_a"> </div> <div class="input-group"> <label for="input9">目標防禦％：</label> <input type="text" id="defense"> </div> <div class="input-group"> <label for="input10">剩餘點數：</label> <input type="text" id="points"> </div> <!-- 其他輸入框 --> <!-- 其他輸入框 --> </form> <button class="calculateBtn", onclick="exampleXenon()">輸入範例</button>'
    document.getElementsByClassName("calculateBtn")[1].setAttribute("onclick", "calculateXenon()") ;
    document.getElementById("output").innerHTML = "";
}
